Vagrant.configure("2") do |config|

	# Load config JSON
	#setup_config_path = "FILE_PATH"
	#setup_config = JSON.parse(File.read(setup_config_path))

	# Base box
	config.vm.box = "precise32"
	config.vm.box_url = "http://files.vagrantup.com/precise32.box"

	# Networking
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network :private_network, ip: "192.168.44.44"

	# Disable default synced folder
	config.vm.synced_folder ".", "/vagrant", disabled: true
	# Add synced folder
	config.vm.synced_folder "data/", "/var/www", owner: "www-data", group: "www-data"

	# Customize provider
	config.vm.provider :virtualbox do |vb|
		# RAM
		vb.customize ["modifyvm", :id, "--memory", "2048"]
	end

	# Customize provisioner
	config.vm.provision :chef_solo do |chef|
		chef.json = {
			"mysql" => {
				"name" => "ac",
				"username" => "root",
				"password" => "root"
			}
		}

		chef.cookbooks_path = [
			"../../lib/chef/cookbooks/opscode",
			"../../lib/chef/cookbooks/vagrant_setup"
		]

		chef.roles_path = [ "../../lib/chef/roles" ]

		chef.add_role "base"
		chef.add_role "lamp"
		chef.add_role "activecollab"
	end

end
